baseURL: "https://hlhs-csie-club.github.io"
copyright: "Belongs to HLHS CSIE CLUB"
author: Algasami/Penquuin
languageCode: zh
DefaultContentLanguage: zh
enableInlineShortcodes: true
theme: tella
enableRobotsTXT: true

title: HLHS CSIE CLUB

markup:
  markup.goldmark:
    markup.goldmark.renderer:
      unsafe: true

font_size_small: 16px

params:
  blogName: Blog
  mainSections:
    - blog
  logo:
    main: img/logo/logo.svg
    alt: Tella Logo
    size: h-14
  site:
    name: HLHS CSIE CLUB
  icon:
    fontawesome: true
  homepage_meta_tags:
    meta_description: ""
    meta_og_title: HLHS CSIE CLUB
    meta_og_type: website
    meta_og_url: "https://hlhs-csie-club.github.io/"
    meta_og_image: "https://raw.githubusercontent.com/hlhs-csie-club/master/static/img/slide/slide01.png"
    meta_og_description: "花中資研社社團網站 The official website of HLHS CSIE Club (Aka the IR Club)"
    meta_twitter_card: summary_large_image
    meta_twitter_site: "@username"
    meta_twitter_creator: "@username"

languages:
  zh:
    languageCode: zh_TW
    languageName: 繁體中文
    weight: 1
    title: 花中資研社
    params:
      blogName: 部落格
    menu:
      main:
        - identifier: activities
          name: 社團活動
          url: /activities/
          weight: 1
        - identifier: blog
          name: 部落格
          url: /blog/
          weight: 2
        - identifier: 關於我們
          name: 關於我們
          url: /about/
          weight: 3
        - identifier: 聯繫方式
          name: 聯繫方式
          url: /contact/
          weight: 4
      footer:
        - name: Home
          url: /
          weight: 1
        - name: Github
          url: "https://github.com/hlhs-csie-club"
          pre: <i class='icon-github text-2xl'></i>
          weight: 2
  en:
    languageCode: en_US
    languageName: English
    weight: 2
    title: HLHS CSIE CLUB
    params:
      blogName: Blog
    menu:
      main:
        - identifier: activities
          name: Activities
          url: /en/activities/
          weight: 1
        - identifier: blog
          name: Blog
          url: /en/blog/
          weight: 2
        - identifier: about
          name: About
          url: /en/about/
          weight: 3
        - identifier: contact
          name: Contact
          url: /en/contact/
          weight: 4
      footer:
        - name: Home
          url: /
          weight: 1
        - name: Github
          url: "https://github.com/hlhs-csie-club"
          pre: <i class='icon-github text-2xl'></i>
          weight: 2
